const PROJECT_TYPES = Object.freeze(["create", "improve"]);

const WORKFLOW_STATUSES = Object.freeze([
  "INTAKE",
  "REVIEW",
  "ARCHITECTURE",
  "MOCKUP",
  "DEVELOPMENT",
  "VALIDATION",
  "PUBLICATION",
  "COMPLETED"
]);

const ITEM_TYPES = Object.freeze([
  "page",
  "service",
  "product",
  "tour",
  "team_member",
  "location",
  "deliverable",
  "custom"
]);

const CREDENTIAL_STATUSES = Object.freeze([
  "NONE",
  "REQUESTED",
  "RECEIVED_OUT_OF_BAND",
  "VERIFIED",
  "REVOKED"
]);

const DOCUMENT_SCAN_STATUSES = Object.freeze([
  "SCAN_NOT_AVAILABLE",
  "UNSCANNED",
  "PENDING",
  "REJECTED"
]);

const REVIEW_VERDICTS = Object.freeze(["APPROVED", "CORRECTION_REQUESTED", "REJECTED"]);
const REVIEW_TARGET_TYPES = Object.freeze([
  "PROJECT",
  "FORM_FIELD",
  "ITEM",
  "DOCUMENT",
  "MOCKUP",
  "MOCKUP_PAGE",
  "MOCKUP_SECTION"
]);
const REVIEW_CURRENT_STATUSES = Object.freeze([
  "PENDING",
  "APPROVED",
  "CORRECTION_REQUIRED",
  "REJECTED"
]);

const AUDIT_ACTIONS = Object.freeze({
  CREATED: "WEB_PROJECT_CREATED",
  UPDATED: "WEB_PROJECT_UPDATED",
  FORM_UPDATED: "WEB_PROJECT_FORM_UPDATED",
  DOCUMENT_REGISTERED: "WEB_PROJECT_DOCUMENT_REGISTERED",
  DOCUMENT_UPLOADED: "WEB_PROJECT_DOCUMENT_UPLOADED",
  DOCUMENT_REPLACED: "WEB_PROJECT_DOCUMENT_REPLACED",
  COMMENT_CREATED: "WEB_PROJECT_COMMENT_CREATED",
  REVIEW_CREATED: "WEB_PROJECT_REVIEW_CREATED",
  REVIEW_APPROVED: "WEB_PROJECT_REVIEW_APPROVED",
  CORRECTION_REQUESTED: "WEB_PROJECT_CORRECTION_REQUESTED",
  CORRECTION_RESUBMITTED: "WEB_PROJECT_CORRECTION_RESUBMITTED",
  TRANSITIONED: "WEB_PROJECT_TRANSITIONED",
  ARCHIVED: "WEB_PROJECT_ARCHIVED",
  ITEM_CREATED: "WEB_PROJECT_ITEM_CREATED",
  CREDENTIAL_STATUS_UPDATED: "WEB_PROJECT_CREDENTIAL_STATUS_UPDATED",
  INVITATION_CREATED: "WEB_PROJECT_INVITATION_CREATED",
  INVITATION_SENT: "WEB_PROJECT_INVITATION_SENT",
  INVITATION_RESENT: "WEB_PROJECT_INVITATION_RESENT",
  INVITATION_REVOKED: "WEB_PROJECT_INVITATION_REVOKED",
  INVITATION_ACCEPTED: "WEB_PROJECT_INVITATION_ACCEPTED",
  CLIENT_ONBOARDED: "WEB_PROJECT_CLIENT_ONBOARDED",
  SELF_SERVICE_STARTED: "WEB_PROJECT_SELF_SERVICE_STARTED",
  SELF_SERVICE_ORGANIZATION_CREATED: "WEB_PROJECT_SELF_SERVICE_ORGANIZATION_CREATED",
  SELF_SERVICE_PROJECT_CREATED: "WEB_PROJECT_SELF_SERVICE_PROJECT_CREATED",
  SUBMITTED_FOR_REVIEW: "WEB_PROJECT_SUBMITTED_FOR_REVIEW",
  BRIEF_NOTE_CREATED: "WEB_PROJECT_BRIEF_NOTE_CREATED",
  BRIEF_NOTE_UPDATED: "WEB_PROJECT_BRIEF_NOTE_UPDATED",
  ARCHITECTURE_STARTED: "WEB_PROJECT_ARCHITECTURE_STARTED",
  ARCHITECTURE_GENERATED: "WEB_PROJECT_ARCHITECTURE_GENERATED",
  ARCHITECTURE_REVISION_CREATED: "WEB_PROJECT_ARCHITECTURE_REVISION_CREATED",
  ARCHITECTURE_APPROVED: "WEB_PROJECT_ARCHITECTURE_APPROVED",
  MOCKUP_STARTED: "WEB_PROJECT_MOCKUP_STARTED",
  MOCKUP_GENERATED: "WEB_PROJECT_MOCKUP_GENERATED",
  MOCKUP_INTERNAL_REVIEW_STARTED: "WEB_PROJECT_MOCKUP_INTERNAL_REVIEW_STARTED",
  MOCKUP_SENT_TO_CLIENT: "WEB_PROJECT_MOCKUP_SENT_TO_CLIENT",
  MOCKUP_CHANGES_REQUESTED: "WEB_PROJECT_MOCKUP_CHANGES_REQUESTED",
  MOCKUP_APPROVED: "WEB_PROJECT_MOCKUP_APPROVED",
  MOCKUP_REVISION_CREATED: "WEB_PROJECT_MOCKUP_REVISION_CREATED",
  DEVELOPMENT_STARTED: "WEB_PROJECT_DEVELOPMENT_STARTED",
  DEVELOPMENT_PLAN_CREATED: "WEB_PROJECT_DEVELOPMENT_PLAN_CREATED",
  DEVELOPMENT_ITEM_STARTED: "WEB_PROJECT_DEVELOPMENT_ITEM_STARTED",
  DEVELOPMENT_ITEM_BLOCKED: "WEB_PROJECT_DEVELOPMENT_ITEM_BLOCKED",
  DEVELOPMENT_ITEM_COMPLETED: "WEB_PROJECT_DEVELOPMENT_ITEM_COMPLETED",
  DEVELOPMENT_READY: "WEB_PROJECT_DEVELOPMENT_READY",
  VALIDATION_STARTED: "WEB_PROJECT_VALIDATION_STARTED",
  VALIDATION_PLAN_CREATED: "WEB_PROJECT_VALIDATION_PLAN_CREATED",
  VALIDATION_RUN_STARTED: "WEB_PROJECT_VALIDATION_RUN_STARTED",
  VALIDATION_CHECK_FAILED: "WEB_PROJECT_VALIDATION_CHECK_FAILED",
  VALIDATION_DEFECT_CREATED: "WEB_PROJECT_VALIDATION_DEFECT_CREATED",
  VALIDATION_DEFECT_FIXED: "WEB_PROJECT_VALIDATION_DEFECT_FIXED",
  VALIDATION_DEFECT_VERIFIED: "WEB_PROJECT_VALIDATION_DEFECT_VERIFIED",
  VALIDATION_READY: "WEB_PROJECT_VALIDATION_READY",
  PUBLICATION_STARTED: "WEB_PROJECT_PUBLICATION_STARTED",
  PUBLICATION_PLAN_CREATED: "WEB_PROJECT_PUBLICATION_PLAN_CREATED",
  PUBLICATION_STEP_STARTED: "WEB_PROJECT_PUBLICATION_STEP_STARTED",
  PUBLICATION_STEP_BLOCKED: "WEB_PROJECT_PUBLICATION_STEP_BLOCKED",
  PUBLICATION_STEP_COMPLETED: "WEB_PROJECT_PUBLICATION_STEP_COMPLETED",
  PUBLICATION_READY: "WEB_PROJECT_PUBLICATION_READY",
  PROJECT_COMPLETED: "WEB_PROJECT_PROJECT_COMPLETED"
});

const BRIEF_NOTE_TYPES = Object.freeze([
  "ARCHITECTURE_NOTE",
  "ASSUMPTION",
  "EXCLUSION",
  "RISK",
  "DECISION_REQUIRED"
]);
const BRIEF_NOTE_STATUSES = Object.freeze(["OPEN", "RESOLVED"]);
const BRIEF_NOTE_SEVERITIES = Object.freeze(["LOW", "MEDIUM", "HIGH"]);
const ARCHITECTURE_READINESS_STATES = Object.freeze(["NOT_READY", "READY_WITH_OPEN_ITEMS", "READY"]);
const BRIEF_SCHEMA_VERSION = "web-project-brief.v1";
const PENDING_DEFINITION = "Pendiente de definir";
const SCOPE_REQUIREMENT_STATES = Object.freeze(["required", "not_required", "pending_decision"]);
const CONTENT_READINESS_STATES = Object.freeze(["READY", "PARTIAL", "MISSING", "NOT_APPLICABLE"]);

const ARCHITECTURE_STATUSES = Object.freeze(["DRAFT", "APPROVED", "SUPERSEDED"]);
const ARCHITECTURE_VALIDATION_STATES = Object.freeze(["INVALID", "READY_WITH_WARNINGS", "READY"]);
const MOCKUP_STATUSES = Object.freeze([
  "DRAFT",
  "INTERNAL_REVIEW",
  "CLIENT_REVIEW",
  "CHANGES_REQUESTED",
  "APPROVED",
  "SUPERSEDED"
]);
const MOCKUP_EDITABLE_STATUSES = Object.freeze(["DRAFT", "INTERNAL_REVIEW"]);
const MOCKUP_VALIDATION_STATES = Object.freeze(["INVALID", "READY_WITH_WARNINGS", "READY"]);
const DEVELOPMENT_HANDOFF_SCHEMA_VERSION = "web-project-development-handoff.v1";
const VALIDATION_HANDOFF_SCHEMA_VERSION = "web-project-validation-handoff.v1";
const DEVELOPMENT_PLAN_STATUSES = Object.freeze(["ACTIVE", "SUPERSEDED"]);
const DEVELOPMENT_ITEM_TYPES = Object.freeze([
  "PROJECT_SETUP",
  "GLOBAL_STYLES",
  "HEADER",
  "FOOTER",
  "PAGE",
  "TEMPLATE",
  "SECTION",
  "CONTENT",
  "MEDIA",
  "FORM",
  "INTEGRATION",
  "SEO",
  "LEGAL",
  "RESPONSIVE",
  "ACCESSIBILITY",
  "PERFORMANCE",
  "ANALYTICS",
  "MIGRATION",
  "REDIRECT",
  "CUSTOM"
]);
const DEVELOPMENT_ITEM_STATUSES = Object.freeze([
  "TODO",
  "READY",
  "IN_PROGRESS",
  "BLOCKED",
  "REVIEW",
  "DONE",
  "NOT_APPLICABLE"
]);
const DEVELOPMENT_ITEM_PRIORITIES = Object.freeze(["LOW", "MEDIUM", "HIGH", "CRITICAL"]);
const DEVELOPMENT_BLOCKER_TYPES = Object.freeze([
  "CLIENT_CONTENT",
  "CLIENT_ASSET",
  "CLIENT_DECISION",
  "INTERNAL_DECISION",
  "TECHNICAL_DEPENDENCY",
  "EXTERNAL_PROVIDER",
  "CREDENTIAL_REQUIRED",
  "LEGAL",
  "OTHER"
]);
const DEVELOPMENT_READINESS_STATES = Object.freeze(["NOT_READY", "READY_WITH_WARNINGS", "READY"]);
const VALIDATION_READINESS_STATES = Object.freeze(["NOT_READY", "READY_WITH_WARNINGS", "READY"]);
const VALIDATION_PLAN_STATUSES = Object.freeze(["ACTIVE", "SUPERSEDED"]);
const VALIDATION_RUN_STATUSES = Object.freeze(["OPEN", "CLOSED"]);
const VALIDATION_CHECK_CATEGORIES = Object.freeze([
  "STRUCTURE",
  "ROUTING",
  "NAVIGATION",
  "CONTENT",
  "MEDIA",
  "VISUAL",
  "RESPONSIVE",
  "FUNCTIONAL",
  "FORM",
  "BOOKING",
  "ECOMMERCE",
  "INTEGRATION",
  "SEO",
  "LEGAL",
  "ACCESSIBILITY",
  "PERFORMANCE",
  "ANALYTICS",
  "SECURITY",
  "MIGRATION",
  "REDIRECT",
  "CUSTOM"
]);
const VALIDATION_CHECK_STATUSES = Object.freeze([
  "PENDING",
  "IN_PROGRESS",
  "PASS",
  "FAIL",
  "BLOCKED",
  "NOT_TESTABLE",
  "NOT_APPLICABLE"
]);
const VALIDATION_DEFECT_SEVERITIES = Object.freeze(["LOW", "MEDIUM", "HIGH", "CRITICAL"]);
const VALIDATION_DEFECT_STATUSES = Object.freeze([
  "OPEN",
  "IN_PROGRESS",
  "FIXED",
  "RETEST_REQUIRED",
  "VERIFIED",
  "WONT_FIX"
]);
const VALIDATION_EVIDENCE_TYPES = Object.freeze([
  "SCREENSHOT",
  "DOCUMENT",
  "URL",
  "TEXT_NOTE",
  "AUTOMATED_RESULT"
]);
const PUBLICATION_HANDOFF_SCHEMA_VERSION = "web-project-publication-handoff.v1";
const COMPLETION_HANDOFF_SCHEMA_VERSION = "web-project-completion-handoff.v1";
const PUBLICATION_PLAN_STATUSES = Object.freeze(["ACTIVE", "SUPERSEDED"]);
const PUBLICATION_STEP_TYPES = Object.freeze([
  "PRELAUNCH_REVIEW",
  "HOSTING_PREP",
  "DNS_PREP",
  "SSL_CERT",
  "STAGING_VERIFY",
  "CONTENT_MIGRATION",
  "REDIRECTS",
  "INTEGRATIONS",
  "ANALYTICS",
  "MONITORING",
  "SEO_LAUNCH",
  "LEGAL_LAUNCH",
  "SMOKE_TEST",
  "CLIENT_HANDOFF",
  "POST_LAUNCH",
  "CUSTOM"
]);
const PUBLICATION_STEP_STATUSES = Object.freeze([
  "TODO",
  "READY",
  "IN_PROGRESS",
  "BLOCKED",
  "REVIEW",
  "DONE",
  "NOT_APPLICABLE"
]);
const PUBLICATION_BLOCKER_TYPES = Object.freeze([
  "CLIENT_CONTENT",
  "CLIENT_DECISION",
  "CLIENT_CREDENTIAL",
  "DNS_PROVIDER",
  "HOSTING_PROVIDER",
  "EXTERNAL_PROVIDER",
  "LEGAL",
  "TECHNICAL",
  "OTHER"
]);
const PUBLICATION_READINESS_STATES = Object.freeze(["NOT_READY", "READY_WITH_WARNINGS", "READY"]);
const DETAIL_TEMPLATE_PAGE_TYPES = Object.freeze(["SERVICE_DETAIL", "PRODUCT_DETAIL", "TOUR_DETAIL", "LOCATION_DETAIL"]);
const ARCHITECTURE_PAGE_TYPES = Object.freeze([
  "HOME",
  "ABOUT",
  "SERVICE_INDEX",
  "SERVICE_DETAIL",
  "PRODUCT_INDEX",
  "PRODUCT_DETAIL",
  "TOUR_INDEX",
  "TOUR_DETAIL",
  "TEAM",
  "LOCATIONS",
  "LOCATION_DETAIL",
  "CONTACT",
  "FAQ",
  "BLOG_INDEX",
  "ARTICLE",
  "LEGAL",
  "BOOKING",
  "ECOMMERCE",
  "LANDING",
  "CUSTOM"
]);
const ARCHITECTURE_TEMPLATE_TYPES = Object.freeze(["UNIQUE", "INDEX", "DETAIL", "LEGAL", "SYSTEM", "LANDING"]);
const ARCHITECTURE_NAV_PLACEMENTS = Object.freeze([
  "PRIMARY",
  "SECONDARY",
  "UTILITY",
  "FOOTER",
  "HIDDEN",
  "NONE"
]);
const ARCHITECTURE_SEO_PRIORITIES = Object.freeze(["HIGH", "MEDIUM", "LOW", "NONE"]);
const ARCHITECTURE_BLOCK_TYPES = Object.freeze([
  "HERO",
  "INTRO",
  "RICH_TEXT",
  "SERVICE_GRID",
  "SERVICE_DETAIL",
  "PRODUCT_GRID",
  "PRODUCT_DETAIL",
  "TOUR_GRID",
  "TOUR_DETAIL",
  "TEAM_GRID",
  "LOCATIONS",
  "FEATURES",
  "BENEFITS",
  "PROCESS",
  "FAQ",
  "TESTIMONIALS",
  "GALLERY",
  "VIDEO",
  "MAP",
  "CONTACT_FORM",
  "QUOTE_FORM",
  "BOOKING_WIDGET",
  "ECOMMERCE_ACTION",
  "CTA",
  "RELATED_CONTENT",
  "NEWS",
  "NEWSLETTER",
  "LEGAL_TEXT",
  "CUSTOM"
]);
const ARCHITECTURE_CONTENT_BINDING_TYPES = Object.freeze([
  "service",
  "product",
  "tour",
  "team_member",
  "location",
  "page",
  "custom"
]);
const ARCHITECTURE_CONTENT_BINDING_MODES = Object.freeze(["collection", "detail", "single"]);
const ARCHITECTURE_MIGRATION_DISPOSITIONS = Object.freeze(["KEEP", "REDESIGN", "MERGE", "REMOVE", "REDIRECT"]);
const ARCHITECTURE_CONVERSION_TYPES = Object.freeze([
  "CONTACT",
  "QUOTE",
  "BOOKING",
  "PURCHASE",
  "CALL",
  "SIGNUP",
  "OTHER"
]);
const CRITICALITY_LEVELS = Object.freeze(["ARCHITECTURE_BLOCKING", "IMPORTANT", "OPTIONAL"]);

const NO_APLICA = "NO_APLICA";

const FORM_SCHEMA_VERSION_V1 = "web-project-intake.v1";
const FORM_SCHEMA_VERSION_V2 = "web-project-intake.v2";
/** Current schema for NEW projects. Historical v1 responses remain readable. */
const FORM_SCHEMA_VERSION = FORM_SCHEMA_VERSION_V2;

const DOCUMENT_CATEGORIES = Object.freeze([
  "LOGO",
  "BRAND_MANUAL",
  "GRAPHIC",
  "TEXT",
  "CATALOG",
  "PRICE_LIST",
  "BROCHURE",
  "PRESENTATION",
  "FAQ",
  "CASE_STUDY",
  "OTHER_CONTENT",
  "TEAM",
  "LOCATION",
  "SERVICE",
  "PRODUCT",
  "TOUR",
  "CORPORATE",
  "VIDEO",
  "LEGAL",
  "OTHER"
]);

/**
 * Client POST creates an INTAKE solicitud only.
 * Staff/NOC creates the expediente in INTAKE.
 * Clients do not pick arbitrary workflow states.
 */
const CLIENT_CREATE_POLICY = "INTAKE_SOLICITUD_ONLY";

const WRITE_ROLES = Object.freeze(["org_owner", "org_admin"]);
const CONTRIBUTE_ROLES = Object.freeze(["org_owner", "org_admin", "org_member"]);
const READ_ROLES = Object.freeze(["org_owner", "org_admin", "org_member", "org_viewer"]);

const MAX_TITLE_LENGTH = 180;
const MAX_HOSTNAME_LENGTH = 253;
const MAX_COMMENT_LENGTH = 4000;
const MAX_ARCHIVE_REASON_LENGTH = 500;
const MAX_FORM_TEXT_LENGTH = 4000;
const MAX_REVIEW_SUMMARY_LENGTH = 2000;
const MAX_FILENAME_LENGTH = 240;
const MAX_ITEM_PAYLOAD_BYTES = 32768;
const MAX_DOCUMENT_BYTES = 20 * 1024 * 1024;

const ITEM_STATUSES = Object.freeze(["draft", "ready", "done"]);

const CLIENT_PATCH_FIELDS = Object.freeze(["title", "websiteHostname", "websiteAssetId"]);
const NOC_PATCH_FIELDS = Object.freeze(["title", "websiteHostname", "websiteAssetId"]);
const PROTECTED_PROJECT_FIELDS = Object.freeze([
  "organizationId",
  "organization_id",
  "createdBy",
  "created_by",
  "workflowStatus",
  "workflow_status",
  "archivedAt",
  "archived_at",
  "archivedBy",
  "archived_by",
  "archiveReason",
  "archive_reason",
  "completedAt",
  "completed_at",
  "submittedForReviewAt",
  "submitted_for_review_at",
  "progress"
]);

const ERROR_CODES = Object.freeze({
  VALIDATION_ERROR: "VALIDATION_ERROR",
  TENANT_REQUIRED: "TENANT_REQUIRED",
  FORBIDDEN: "FORBIDDEN",
  NOT_FOUND: "NOT_FOUND",
  INVALID_TRANSITION: "INVALID_TRANSITION",
  PROJECT_ARCHIVED: "PROJECT_ARCHIVED",
  PROJECT_COMPLETED: "PROJECT_COMPLETED",
  ARCHIVE_NOT_ELIGIBLE: "ARCHIVE_NOT_ELIGIBLE",
  INVALID_FORM_FIELD: "INVALID_FORM_FIELD",
  INVALID_FORM_VALUE: "INVALID_FORM_VALUE",
  UNSUPPORTED_ITEM_TYPE: "UNSUPPORTED_ITEM_TYPE",
  SECRET_REJECTED: "SECRET_REJECTED",
  DOCUMENT_INVALID: "DOCUMENT_INVALID",
  STORAGE_UNAVAILABLE: "STORAGE_UNAVAILABLE",
  REVIEW_TARGET_INVALID: "REVIEW_TARGET_INVALID",
  REVIEW_ALREADY_RESOLVED: "REVIEW_ALREADY_RESOLVED",
  CORRECTION_MESSAGE_REQUIRED: "CORRECTION_MESSAGE_REQUIRED",
  REPLACEMENT_INVALID: "REPLACEMENT_INVALID",
  ORGANIZATION_NOT_FOUND: "ORGANIZATION_NOT_FOUND",
  MEMBERSHIP_REQUIRED: "MEMBERSHIP_REQUIRED",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  INVITATION_INVALID: "INVITATION_INVALID",
  WRONG_ACCOUNT: "WRONG_ACCOUNT",
  LOGIN_REQUIRED: "LOGIN_REQUIRED",
  SETUP_REQUIRED: "SETUP_REQUIRED",
  ORG_SELECTION_REQUIRED: "ORG_SELECTION_REQUIRED",
  INACTIVE_ORGANIZATION: "INACTIVE_ORGANIZATION",
  INCOMPLETE_SUBMISSION: "INCOMPLETE_SUBMISSION",
  FORM_LOCKED: "FORM_LOCKED",
  INVALID_ITEM_PAYLOAD: "INVALID_ITEM_PAYLOAD",
  ARCHITECTURE_NOT_READY: "ARCHITECTURE_NOT_READY",
  ARCHITECTURE_OVERRIDE_REQUIRED: "ARCHITECTURE_OVERRIDE_REQUIRED",
  BRIEF_NOTE_INVALID: "BRIEF_NOTE_INVALID",
  ARCHITECTURE_NOT_EDITABLE: "ARCHITECTURE_NOT_EDITABLE",
  ARCHITECTURE_DRAFT_EXISTS: "ARCHITECTURE_DRAFT_EXISTS",
  ARCHITECTURE_NOT_APPROVED: "ARCHITECTURE_NOT_APPROVED",
  ARCHITECTURE_INVALID: "ARCHITECTURE_INVALID",
  ARCHITECTURE_WORKFLOW_BLOCKED: "ARCHITECTURE_WORKFLOW_BLOCKED",
  MOCKUP_NOT_READY: "MOCKUP_NOT_READY",
  MOCKUP_OVERRIDE_REQUIRED: "MOCKUP_OVERRIDE_REQUIRED",
  MOCKUP_WORKFLOW_BLOCKED: "MOCKUP_WORKFLOW_BLOCKED",
  MOCKUP_NOT_EDITABLE: "MOCKUP_NOT_EDITABLE",
  MOCKUP_DRAFT_EXISTS: "MOCKUP_DRAFT_EXISTS",
  MOCKUP_INVALID: "MOCKUP_INVALID",
  PREVIEW_ITEM_INCOMPATIBLE: "PREVIEW_ITEM_INCOMPATIBLE",
  PREVIEW_ITEM_NOT_FOUND: "PREVIEW_ITEM_NOT_FOUND",
  PREVIEW_NOT_APPLICABLE: "PREVIEW_NOT_APPLICABLE",
  DEVELOPMENT_NOT_READY: "DEVELOPMENT_NOT_READY",
  DEVELOPMENT_PLAN_EXISTS: "DEVELOPMENT_PLAN_EXISTS",
  DEVELOPMENT_WORKFLOW_BLOCKED: "DEVELOPMENT_WORKFLOW_BLOCKED",
  DEVELOPMENT_ITEM_INVALID: "DEVELOPMENT_ITEM_INVALID",
  DEVELOPMENT_ITEM_NOT_EDITABLE: "DEVELOPMENT_ITEM_NOT_EDITABLE",
  DEVELOPMENT_DEPENDENCY_INVALID: "DEVELOPMENT_DEPENDENCY_INVALID",
  DEVELOPMENT_DEPENDENCY_CYCLE: "DEVELOPMENT_DEPENDENCY_CYCLE",
  DEVELOPMENT_BLOCKER_REQUIRED: "DEVELOPMENT_BLOCKER_REQUIRED",
  VALIDATION_NOT_READY: "VALIDATION_NOT_READY",
  VALIDATION_OVERRIDE_REQUIRED: "VALIDATION_OVERRIDE_REQUIRED",
  VALIDATION_WORKFLOW_BLOCKED: "VALIDATION_WORKFLOW_BLOCKED",
  VALIDATION_PLAN_EXISTS: "VALIDATION_PLAN_EXISTS",
  VALIDATION_CHECK_INVALID: "VALIDATION_CHECK_INVALID",
  VALIDATION_DEFECT_INVALID: "VALIDATION_DEFECT_INVALID",
  PUBLICATION_NOT_READY: "PUBLICATION_NOT_READY",
  PUBLICATION_OVERRIDE_REQUIRED: "PUBLICATION_OVERRIDE_REQUIRED",
  PUBLICATION_WORKFLOW_BLOCKED: "PUBLICATION_WORKFLOW_BLOCKED",
  PUBLICATION_PLAN_EXISTS: "PUBLICATION_PLAN_EXISTS",
  PUBLICATION_STEP_INVALID: "PUBLICATION_STEP_INVALID",
  PUBLICATION_BLOCKER_REQUIRED: "PUBLICATION_BLOCKER_REQUIRED",
  COMPLETION_NOT_READY: "COMPLETION_NOT_READY",
  COMPLETION_OVERRIDE_REQUIRED: "COMPLETION_OVERRIDE_REQUIRED",
  ARCHITECTURE_PAGE_INVALID: "ARCHITECTURE_PAGE_INVALID",
  ARCHITECTURE_BLOCK_INVALID: "ARCHITECTURE_BLOCK_INVALID"
});

const ALLOWED_DOCUMENT_MIME = Object.freeze([
  "application/pdf",
  "application/msword",
  "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
  "application/vnd.ms-excel",
  "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
  "application/vnd.ms-powerpoint",
  "application/vnd.openxmlformats-officedocument.presentationml.presentation",
  "text/plain",
  "text/csv",
  "image/jpeg",
  "image/png",
  "image/webp",
  "image/svg+xml"
]);

const MIME_EXTENSION = Object.freeze({
  "application/pdf": [".pdf"],
  "application/msword": [".doc"],
  "application/vnd.openxmlformats-officedocument.wordprocessingml.document": [".docx"],
  "application/vnd.ms-excel": [".xls"],
  "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet": [".xlsx"],
  "application/vnd.ms-powerpoint": [".ppt"],
  "application/vnd.openxmlformats-officedocument.presentationml.presentation": [".pptx"],
  "text/plain": [".txt"],
  "text/csv": [".csv"],
  "image/jpeg": [".jpg", ".jpeg"],
  "image/png": [".png"],
  "image/webp": [".webp"],
  "image/svg+xml": [".svg"]
});

module.exports = {
  PROJECT_TYPES,
  WORKFLOW_STATUSES,
  ITEM_TYPES,
  CREDENTIAL_STATUSES,
  DOCUMENT_SCAN_STATUSES,
  REVIEW_VERDICTS,
  REVIEW_TARGET_TYPES,
  REVIEW_CURRENT_STATUSES,
  AUDIT_ACTIONS,
  BRIEF_NOTE_TYPES,
  BRIEF_NOTE_STATUSES,
  BRIEF_NOTE_SEVERITIES,
  ARCHITECTURE_READINESS_STATES,
  BRIEF_SCHEMA_VERSION,
  PENDING_DEFINITION,
  SCOPE_REQUIREMENT_STATES,
  CONTENT_READINESS_STATES,
  ARCHITECTURE_STATUSES,
  ARCHITECTURE_VALIDATION_STATES,
  MOCKUP_STATUSES,
  MOCKUP_EDITABLE_STATUSES,
  MOCKUP_VALIDATION_STATES,
  DEVELOPMENT_HANDOFF_SCHEMA_VERSION,
  VALIDATION_HANDOFF_SCHEMA_VERSION,
  DEVELOPMENT_PLAN_STATUSES,
  DEVELOPMENT_ITEM_TYPES,
  DEVELOPMENT_ITEM_STATUSES,
  DEVELOPMENT_ITEM_PRIORITIES,
  DEVELOPMENT_BLOCKER_TYPES,
  DEVELOPMENT_READINESS_STATES,
  VALIDATION_READINESS_STATES,
  VALIDATION_PLAN_STATUSES,
  VALIDATION_RUN_STATUSES,
  VALIDATION_CHECK_CATEGORIES,
  VALIDATION_CHECK_STATUSES,
  VALIDATION_DEFECT_SEVERITIES,
  VALIDATION_DEFECT_STATUSES,
  VALIDATION_EVIDENCE_TYPES,
  PUBLICATION_HANDOFF_SCHEMA_VERSION,
  COMPLETION_HANDOFF_SCHEMA_VERSION,
  PUBLICATION_PLAN_STATUSES,
  PUBLICATION_STEP_TYPES,
  PUBLICATION_STEP_STATUSES,
  PUBLICATION_BLOCKER_TYPES,
  PUBLICATION_READINESS_STATES,
  DETAIL_TEMPLATE_PAGE_TYPES,
  ARCHITECTURE_PAGE_TYPES,
  ARCHITECTURE_TEMPLATE_TYPES,
  ARCHITECTURE_NAV_PLACEMENTS,
  ARCHITECTURE_SEO_PRIORITIES,
  ARCHITECTURE_BLOCK_TYPES,
  ARCHITECTURE_CONTENT_BINDING_TYPES,
  ARCHITECTURE_CONTENT_BINDING_MODES,
  ARCHITECTURE_MIGRATION_DISPOSITIONS,
  ARCHITECTURE_CONVERSION_TYPES,
  CRITICALITY_LEVELS,
  NO_APLICA,
  FORM_SCHEMA_VERSION_V1,
  FORM_SCHEMA_VERSION_V2,
  FORM_SCHEMA_VERSION,
  DOCUMENT_CATEGORIES,
  CLIENT_CREATE_POLICY,
  WRITE_ROLES,
  CONTRIBUTE_ROLES,
  READ_ROLES,
  MAX_TITLE_LENGTH,
  MAX_HOSTNAME_LENGTH,
  MAX_COMMENT_LENGTH,
  MAX_ARCHIVE_REASON_LENGTH,
  MAX_FORM_TEXT_LENGTH,
  MAX_REVIEW_SUMMARY_LENGTH,
  MAX_FILENAME_LENGTH,
  MAX_ITEM_PAYLOAD_BYTES,
  MAX_DOCUMENT_BYTES,
  ITEM_STATUSES,
  CLIENT_PATCH_FIELDS,
  NOC_PATCH_FIELDS,
  PROTECTED_PROJECT_FIELDS,
  ERROR_CODES,
  ALLOWED_DOCUMENT_MIME,
  MIME_EXTENSION
};
