const REPORT_TYPE_INCIDENT_SUMMARY = "INCIDENT_SUMMARY";
const TEMPLATE_VERSION = "1.0.0";
const SCHEMA_VERSION = "1.0.0";

const REPORT_RUN_STATUS = Object.freeze([
  "REQUESTED",
  "QUEUED",
  "GENERATING",
  "STORING",
  "READY",
  "FAILED",
  "EXPIRED"
]);

const ALLOWED_JOB_TYPES = Object.freeze(["REPORT_GENERATE", "NOTIFICATION_DELIVER"]);

const NOTIFICATION_EVENT_REPORT_READY = "REPORT_READY";

module.exports = {
  REPORT_TYPE_INCIDENT_SUMMARY,
  TEMPLATE_VERSION,
  SCHEMA_VERSION,
  REPORT_RUN_STATUS,
  ALLOWED_JOB_TYPES,
  NOTIFICATION_EVENT_REPORT_READY
};
